version: '3.8'

services:
  appdb:
    image: postgres:latest
    container_name: appdb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - appdb_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  appdb_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: 'appdb:5432'
      ALLOW_ADDR_REGEX: '.*'
      LOG_TRAFFIC: 'true'
    ports:
      - '5433:80'
    depends_on:
      - appdb

volumes:
  appdb_data:
